"""
api.py
======
FastAPI application exposing the trained ML models and the RAG assistant
over HTTP.

Endpoints
---------
GET  /health             -- Liveness probe; returns {"status": "ok"}.
POST /predict_discount   -- Predict discount_percentage with drift detection.
POST /answer_question    -- Answer a product-related question via RAG + LLM.

Startup behaviour
-----------------
All heavyweight objects (the sklearn model, the FAISS index, the sentence-
transformer embedding model) are loaded once inside the ``lifespan`` async
context manager and stored on ``app.state``.  This means:

- Each HTTP request is served from in-memory objects with no disk I/O.
- Missing artifact files produce clear WARNING messages at startup rather
  than crashing — the affected endpoints will return HTTP 503 with an
  actionable error message until ``train.py`` is run.

Running the server
------------------
From the project root::

    uvicorn src.api:app --reload          # development
    uvicorn src.api:app --host 0.0.0.0    # production / Docker

Or via Docker Compose::

    docker compose up --build

Interactive API docs (auto-generated by FastAPI) are available at
http://localhost:8000/docs once the server is running.
"""

import os
from contextlib import asynccontextmanager
from typing import Any

import numpy as np
from fastapi import FastAPI, HTTPException, Request
from pydantic import BaseModel

from src.models import check_drift, load_model
from src.rag import generate_answer, load_faiss_index, retrieve_relevant_docs

ARTIFACTS_DIR = os.path.join(os.path.dirname(__file__), "..", "artifacts")
STATS_PATH = os.path.join(ARTIFACTS_DIR, "training_stats.json")


# ── Application lifespan ──────────────────────────────────────────────────────

@asynccontextmanager
async def lifespan(app: FastAPI):
    """Load all model artifacts once at server startup and tear down on stop.

    FastAPI's ``lifespan`` replaces the older ``@app.on_event("startup")``
    pattern.  Code before ``yield`` runs at startup; code after runs at
    shutdown (nothing to clean up here since models are in-memory objects).

    All loading is wrapped in ``try/except FileNotFoundError`` so a missing
    artifact produces a clear warning rather than a crash.  The affected
    endpoints will return HTTP 503 until the user runs ``python train.py``.
    """
    # ── Discount prediction model ─────────────────────────────────────────
    try:
        app.state.discount_model = load_model("random_forest_discount")
        print("Discount model loaded.")
    except FileNotFoundError:
        app.state.discount_model = None
        print("WARNING: Discount model not found — run train.py first.")

    # ── RAG index (FAISS + embedding model + document corpus) ─────────────
    try:
        index, embed_model, documents = load_faiss_index()
        app.state.rag_index = index
        app.state.rag_embed = embed_model
        app.state.rag_docs = documents
        print(f"RAG index loaded ({len(documents)} documents).")
    except FileNotFoundError:
        app.state.rag_index = None
        app.state.rag_embed = None
        app.state.rag_docs = None
        print("WARNING: RAG index not found — run train.py first.")

    # ── Drift detection stats ─────────────────────────────────────────────
    # Store the path (not the loaded dict) so check_drift can re-read it if
    # the file is updated without restarting the server.
    app.state.stats_path = STATS_PATH if os.path.exists(STATS_PATH) else None

    yield  # Server runs while suspended here.


# ── App instance ──────────────────────────────────────────────────────────────

app = FastAPI(
    title="Marketing Data Intelligence API",
    version="1.0.0",
    description=(
        "Discount percentage prediction (RandomForest) and an AI product "
        "assistant powered by FAISS retrieval and google/flan-t5-base."
    ),
    lifespan=lifespan,
)


# ── Request / response schemas ────────────────────────────────────────────────

class DiscountRequest(BaseModel):
    """Input schema for the /predict_discount endpoint.

    All four fields are required.  They correspond to the features the
    RandomForest model was trained on.

    Attributes:
        actual_price: The product's original / MRP price in Indian Rupees.
        discounted_price: The current selling price in Indian Rupees.  Must
            be less than ``actual_price`` for a meaningful prediction.
        rating: Average customer star rating on a 1–5 scale.
        rating_count: Total number of customer ratings.
    """

    actual_price: float
    discounted_price: float
    rating: float
    rating_count: float


class QuestionRequest(BaseModel):
    """Input schema for the /answer_question endpoint.

    Attributes:
        query: Free-text question about products in the catalog.
        top_k: Number of product documents to retrieve from FAISS before
            passing them to the LLM as context.  Higher values give the model
            more information but also more noise.  Defaults to 3.
    """

    query: str
    top_k: int = 3


# ── Endpoints ─────────────────────────────────────────────────────────────────

@app.get("/health", summary="Liveness probe")
def health():
    """Return a simple OK response to confirm the server is running.

    Intended for use by load balancers, Docker HEALTHCHECK instructions,
    and monitoring systems.  Does not verify that the ML models are loaded.
    """
    return {"status": "ok"}


@app.post("/predict_discount", summary="Predict discount percentage")
def predict_discount(body: DiscountRequest, request: Request):
    """Predict the discount percentage for a product using the trained RandomForest.

    In addition to the predicted value, the response includes a drift warning
    that flags when the input features are statistically unusual compared to
    the training data distribution.

    Args:
        body: Product attributes — see ``DiscountRequest``.
        request: FastAPI request object used to access ``app.state`` where
            the model and drift stats were loaded at startup.

    Returns:
        JSON with four keys:
        - ``predicted_discount_percentage`` (float): The model's prediction,
          rounded to 2 decimal places.
        - ``drift_warning`` (bool): ``true`` if any feature is more than
          3 standard deviations from its training mean.
        - ``drift_details`` (dict): Per-feature z-scores for transparency.
        - ``inputs`` (dict): Echo of the request body for convenience.

    Raises:
        HTTPException 503: If the discount model was not found at startup.
    """
    model = request.app.state.discount_model
    if model is None:
        raise HTTPException(
            status_code=503,
            detail="Discount model not loaded. Run python train.py first.",
        )

    # sklearn expects a 2-D array even for a single sample.
    features = np.array(
        [[body.actual_price, body.discounted_price, body.rating, body.rating_count]]
    )
    prediction = float(model.predict(features)[0])

    # Drift check is optional — it requires training_stats.json to exist.
    drift_info: dict[str, Any] = {}
    stats_path = request.app.state.stats_path
    if stats_path:
        # model_dump() includes all four feature fields plus no extras (Pydantic
        # strips unknown keys), so it maps cleanly onto the stats keys.
        drift_info = check_drift(body.model_dump(), stats_path)

    return {
        "predicted_discount_percentage": round(prediction, 2),
        "drift_warning": drift_info.get("drift_detected", False),
        "drift_details": drift_info.get("z_scores", {}),
        "inputs": body.model_dump(),
    }


@app.post("/answer_question", summary="Answer a product question via RAG + LLM")
def answer_question(body: QuestionRequest, request: Request):
    """Answer a product-related question using retrieval-augmented generation.

    Pipeline:
    1. Embed ``query`` with ``all-MiniLM-L6-v2``.
    2. Retrieve the ``top_k`` nearest product documents from FAISS.
    3. Build an instruction prompt containing the retrieved context.
    4. Generate an answer with ``google/flan-t5-base`` (or the model
       configured via the ``LLM_MODEL`` environment variable).

    Args:
        body: Contains ``query`` (required) and ``top_k`` (optional, default 3).
        request: FastAPI request object used to access ``app.state``.

    Returns:
        JSON with three keys:
        - ``question`` (str): The original query, echoed for clarity.
        - ``answer`` (str): The LLM-generated response, grounded in the
          retrieved product documents.
        - ``sources`` (list[str]): The raw document strings that were passed
          to the LLM as context.  Useful for verifying grounding and
          displaying citations in the UI.

    Raises:
        HTTPException 503: If the RAG index was not found at startup.

    Note:
        The first call to this endpoint will trigger the LLM to be loaded
        into memory, which takes several seconds.  Subsequent calls are fast.
    """
    index = request.app.state.rag_index
    embed_model = request.app.state.rag_embed
    documents = request.app.state.rag_docs

    if index is None:
        raise HTTPException(
            status_code=503,
            detail="RAG index not loaded. Run python train.py first.",
        )

    top_docs = retrieve_relevant_docs(
        body.query, index, embed_model, documents, top_k=body.top_k
    )
    answer = generate_answer(body.query, top_docs)

    return {
        "question": body.query,
        "answer": answer,
        "sources": top_docs,
    }
